# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: |
        javac -cp ./target/classes Bank_admin_menu.java
        java -cp ./target/classes Bank_admin_menu

        javac -cp ./target/classes Exception_handle.java
        java -cp ./target/classes Exception_handle

        javac -cp ./target/classes Mark.java
        java -cp ./target/classes Mark

        javac -cp ./target/classes Multilevel_Inheritence.java
        java -cp ./target/classes Multilevel_Inheritence
